timeout 1h time maude-se-yices2 t4-c-n.maude &> log-abs-t4-c-n-gcd1.log &
timeout 1h time maude-se-yices2 t4-c-a.maude &> log-abs-t4-c-a-gcd1.log &
timeout 1h time maude-se-yices2 t4-c-i.maude &> log-abs-t4-c-i-gcd1.log &
timeout 1h time maude-se-yices2 t4-c-p.maude &> log-abs-t4-c-p-gcd1.log &
timeout 1h time maude-se-yices2 t4-c-n-gcd2.maude &> log-abs-t4-c-n-gcd2.log &
timeout 1h time maude-se-yices2 t4-c-a-gcd2.maude &> log-abs-t4-c-a-gcd2.log &
timeout 1h time maude-se-yices2 t4-c-i-gcd2.maude &> log-abs-t4-c-i-gcd2.log &
timeout 1h time maude-se-yices2 t4-c-p-gcd2.maude &> log-abs-t4-c-p-gcd2.log &
timeout 1h time maude-se-yices2 t4-c-n-gcd3.maude &> log-abs-t4-c-n-gcd3.log &
timeout 1h time maude-se-yices2 t4-c-a-gcd3.maude &> log-abs-t4-c-a-gcd3.log &
timeout 1h time maude-se-yices2 t4-c-i-gcd3.maude &> log-abs-t4-c-i-gcd3.log &
timeout 1h time maude-se-yices2 t4-c-p-gcd3.maude &> log-abs-t4-c-p-gcd3.log &

timeout 1h time maude-se-yices2 t4-s-n.maude &> log-abs-t4-s-n-gcd1.log &
timeout 1h time maude-se-yices2 t4-s-a.maude &> log-abs-t4-s-a-gcd1.log &
timeout 1h time maude-se-yices2 t4-s-i.maude &> log-abs-t4-s-i-gcd1.log &
timeout 1h time maude-se-yices2 t4-s-p.maude &> log-abs-t4-s-p-gcd1.log &
timeout 1h time maude-se-yices2 t4-s-n-gcd2.maude &> log-abs-t4-s-n-gcd2.log &
timeout 1h time maude-se-yices2 t4-s-a-gcd2.maude &> log-abs-t4-s-a-gcd2.log &
timeout 1h time maude-se-yices2 t4-s-i-gcd2.maude &> log-abs-t4-s-i-gcd2.log &
timeout 1h time maude-se-yices2 t4-s-p-gcd2.maude &> log-abs-t4-s-p-gcd2.log &
timeout 1h time maude-se-yices2 t4-s-n-gcd3.maude &> log-abs-t4-s-n-gcd3.log &
timeout 1h time maude-se-yices2 t4-s-a-gcd3.maude &> log-abs-t4-s-a-gcd3.log &
timeout 1h time maude-se-yices2 t4-s-i-gcd3.maude &> log-abs-t4-s-i-gcd3.log &
timeout 1h time maude-se-yices2 t4-s-p-gcd3.maude &> log-abs-t4-s-p-gcd3.log &
