timeout 5h time maude-se-yices2 cb2-c-n.maude &> log-gcd-cb2-c-n-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-c-a.maude &> log-gcd-cb2-c-a-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-c-i.maude &> log-gcd-cb2-c-i-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-c-p.maude &> log-gcd-cb2-c-p-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-c-n-gcd2.maude &> log-gcd-cb2-c-n-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-c-a-gcd2.maude &> log-gcd-cb2-c-a-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-c-i-gcd2.maude &> log-gcd-cb2-c-i-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-c-p-gcd2.maude &> log-gcd-cb2-c-p-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-c-n-gcd3.maude &> log-gcd-cb2-c-n-gcd3-state.log &
timeout 5h time maude-se-yices2 cb2-c-a-gcd3.maude &> log-gcd-cb2-c-a-gcd3-state.log &
timeout 5h time maude-se-yices2 cb2-c-i-gcd3.maude &> log-gcd-cb2-c-i-gcd3-state.log &
timeout 5h time maude-se-yices2 cb2-c-p-gcd3.maude &> log-gcd-cb2-c-p-gcd3-state.log &

timeout 5h time maude-se-yices2 cb2-s-n.maude &> log-gcd-cb2-s-n-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-s-a.maude &> log-gcd-cb2-s-a-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-s-i.maude &> log-gcd-cb2-s-i-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-s-p.maude &> log-gcd-cb2-s-p-gcd1-state.log &
timeout 5h time maude-se-yices2 cb2-s-n-gcd2.maude &> log-gcd-cb2-s-n-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-s-a-gcd2.maude &> log-gcd-cb2-s-a-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-s-i-gcd2.maude &> log-gcd-cb2-s-i-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-s-p-gcd2.maude &> log-gcd-cb2-s-p-gcd2-state.log &
timeout 5h time maude-se-yices2 cb2-s-n-gcd3.maude &> log-gcd-cb2-s-n-gcd3-state.log &
timeout 5h time maude-se-yices2 cb2-s-a-gcd3.maude &> log-gcd-cb2-s-a-gcd3-state.log &
timeout 5h time maude-se-yices2 cb2-s-i-gcd3.maude &> log-gcd-cb2-s-i-gcd3-state.log &
timeout 5h time maude-se-yices2 cb2-s-p-gcd3.maude &> log-gcd-cb2-s-p-gcd3-state.log &
